### ISSUE TITLE
Get list of followers

### ISSUE THREAD

**Issue by kutyel** [chshersh/sauron#12]
Hi! I want to be able to sort my followers by a certain criteria (such as their follow base for example) and I am not able to, maybe I could work in getting this feat to sauron! 🤔

**Comment by chshersh** [comment]
Hi @kutyel 👋🏻 

`sauron` no longer works with some of the recent changes to Twitter API. At least I wasn't able to make it work.

I was planning to archive this project but haven't got the time for it.

**Comment by kutyel** [comment]
Hey, that is Ok, thanks for letting me know! 😉
